---
- name: Gather facts
  hosts: sfs
  become: yes

  tasks:

    - debug:
        msg:
          - "{{ansible_fqdn}}"
          - "{{ansible_distribution}}" 

    - debug:
        msg:
          - "{{ansible_default_ipv4}}"